import type { PuzzleDefinition, PuzzleId } from "./types";

export const puzzleCatalog: PuzzleDefinition[] = [
  {
    id: "sudoku",
    title: "Sudoku",
    tagline: "Classic number-placement grids.",
    description: "Generate seeded 9 by 9 Sudoku-style boards, then click open cells to cycle digits.",
    category: "numbers",
    status: "playable",
    tags: ["numbers", "deduction", "grid"],
    defaultWidth: 9,
    defaultHeight: 9,
    minWidth: 9,
    maxWidth: 9,
    minHeight: 9,
    maxHeight: 9,
  },
  {
    id: "nonogram",
    title: "Nonogram",
    tagline: "Picture logic from row and column clues.",
    description: "Generate seeded Nonogram clue boards and click cells to mark or clear filled squares.",
    category: "grid",
    status: "playable",
    tags: ["logic", "picture", "grid"],
    defaultWidth: 8,
    defaultHeight: 8,
    minWidth: 5,
    maxWidth: 12,
    minHeight: 5,
    maxHeight: 12,
  },
  {
    id: "wordle",
    title: "Wordle-like",
    tagline: "Compact word deduction loops.",
    description: "Generate seeded sample rows and click the open row to cycle letters into a guess.",
    category: "word",
    status: "playable",
    tags: ["word", "deduction", "daily"],
    defaultWidth: 5,
    defaultHeight: 6,
    minWidth: 5,
    maxWidth: 5,
    minHeight: 6,
    maxHeight: 6,
  },
  {
    id: "logic-grid",
    title: "Logic Grid",
    tagline: "Seeded numeric clue workbenches.",
    description: "Generate deterministic clue grids and click open cells to cycle candidate digits.",
    category: "logic",
    status: "playable",
    tags: ["logic", "procedural", "sandbox"],
    defaultWidth: 6,
    defaultHeight: 6,
    minWidth: 4,
    maxWidth: 12,
    minHeight: 4,
    maxHeight: 12,
  },
  {
    id: "klondike-solitaire",
    title: "Solitaire",
    tagline: "Seeded 52-card Klondike deals.",
    description: "Generate deterministic Klondike deals, draw from stock, and move legal cards to tableau or foundations.",
    category: "cards",
    status: "playable",
    tags: ["cards", "solitaire", "klondike", "52-card"],
    defaultWidth: 7,
    defaultHeight: 7,
    minWidth: 7,
    maxWidth: 7,
    minHeight: 7,
    maxHeight: 7,
  },
  {
    id: "peg-solitaire",
    title: "Peg Solitaire",
    tagline: "Jumping pegs on classic cross boards.",
    description: "Generate seeded English peg-solitaire starts, then select pegs and jump into empty holes.",
    category: "logic",
    status: "playable",
    tags: ["logic", "solitaire", "jumping", "grid"],
    defaultWidth: 7,
    defaultHeight: 7,
    minWidth: 7,
    maxWidth: 7,
    minHeight: 7,
    maxHeight: 7,
  },
  {
    id: "kenken",
    title: "KenKen",
    tagline: "Arithmetic cages over Latin-square grids.",
    description: "Planned: generate cages, operators, and solver-friendly validation metadata.",
    category: "numbers",
    status: "planned",
    tags: ["numbers", "arithmetic", "cages"],
    defaultWidth: 6,
    defaultHeight: 6,
    minWidth: 4,
    maxWidth: 9,
    minHeight: 4,
    maxHeight: 9,
  },
  {
    id: "minesweeper",
    title: "Minesweeper",
    tagline: "Risky reveal logic and probability surfaces.",
    description: "Planned: generate minefields with first-click safety and solver annotations.",
    category: "grid",
    status: "planned",
    tags: ["grid", "probability", "classic"],
    defaultWidth: 10,
    defaultHeight: 10,
    minWidth: 8,
    maxWidth: 16,
    minHeight: 8,
    maxHeight: 16,
  },
  {
    id: "slitherlink",
    title: "Slitherlink",
    tagline: "Loop constraints around numbered cells.",
    description: "Planned: generate loop puzzles with uniqueness checks and path constraints.",
    category: "logic",
    status: "planned",
    tags: ["loop", "logic", "constraints"],
    defaultWidth: 7,
    defaultHeight: 7,
    minWidth: 5,
    maxWidth: 12,
    minHeight: 5,
    maxHeight: 12,
  },
];

export const getPuzzleDefinition = (id: PuzzleId) =>
  puzzleCatalog.find((puzzle) => puzzle.id === id) ?? puzzleCatalog[0];

export const isGeneratable = (puzzle: PuzzleDefinition) => puzzle.status !== "planned";
