import type { PuzzleDefinition, PuzzleId } from "./types";

export const puzzleCatalog: PuzzleDefinition[] = [
  {
    id: "sudoku",
    title: "Sudoku",
    tagline: "Classic 9x9 logic with seeded difficulty.",
    description: "Fill every row, column, and 3x3 box with digits 1-9.",
    category: "numbers",
    status: "playable",
    tags: ["numbers", "deduction", "grid"],
    defaultWidth: 9,
    defaultHeight: 9,
    minWidth: 9,
    maxWidth: 9,
    minHeight: 9,
    maxHeight: 9,
  },
  {
    id: "nonogram",
    title: "Nonogram",
    tagline: "Picture logic from row and column clues.",
    description: "Generate seeded Nonogram clue boards, mark cells, and check the completed picture grid.",
    category: "grid",
    status: "playable",
    tags: ["logic", "picture", "grid"],
    defaultWidth: 8,
    defaultHeight: 8,
    minWidth: 5,
    maxWidth: 12,
    minHeight: 5,
    maxHeight: 12,
  },
  {
    id: "word-guess",
    title: "Word Guess",
    tagline: "Letter-position deduction with seeded answers.",
    description: "Generate a seeded answer, type letter guesses, and check duplicate-aware exact and present letters across configurable word lengths and attempt counts.",
    category: "word",
    status: "playable",
    tags: ["word", "deduction", "daily"],
    defaultWidth: 5,
    defaultHeight: 6,
    minWidth: 4,
    maxWidth: 12,
    minHeight: 4,
    maxHeight: 10,
  },
  {
    id: "logic-grid",
    title: "Logic Grid",
    tagline: "Seeded numeric clue workbenches.",
    description: "Planned: generate deterministic clue grids, type candidate digits, and check against the generated solution.",
    category: "logic",
    status: "planned",
    tags: ["logic", "procedural", "sandbox"],
    defaultWidth: 6,
    defaultHeight: 6,
    minWidth: 4,
    maxWidth: 12,
    minHeight: 4,
    maxHeight: 12,
  },
  {
    id: "klondike-solitaire",
    title: "Solitaire",
    tagline: "Preview: seeded 52-card Klondike deals.",
    description: "Preview: generate deterministic Klondike deals, draw from stock, and move legal cards to tableau or foundations.",
    category: "cards",
    status: "prototype",
    tags: ["cards", "solitaire", "klondike", "52-card"],
    defaultWidth: 7,
    defaultHeight: 7,
    minWidth: 7,
    maxWidth: 7,
    minHeight: 7,
    maxHeight: 7,
  },
  {
    id: "jigsaw",
    title: "Jigsaw",
    tagline: "Seeded square-tile image assembly.",
    description: "Generate deterministic square-tile Jigsaw layouts, preview the generated artwork, and swap tiles into place.",
    category: "grid",
    status: "playable",
    tags: ["image", "tiles", "spatial", "seeded"],
    defaultWidth: 4,
    defaultHeight: 4,
    minWidth: 2,
    maxWidth: 8,
    minHeight: 2,
    maxHeight: 8,
  },
  {
    id: "peg-solitaire",
    title: "Peg Solitaire",
    tagline: "Jumping pegs on classic cross boards.",
    description: "Planned: generate seeded English peg-solitaire starts, then select pegs and jump into empty holes.",
    category: "logic",
    status: "planned",
    tags: ["logic", "solitaire", "jumping", "grid"],
    defaultWidth: 7,
    defaultHeight: 7,
    minWidth: 7,
    maxWidth: 7,
    minHeight: 7,
    maxHeight: 7,
  },
  {
    id: "kenken",
    title: "KenKen",
    tagline: "Arithmetic cages over Latin-square grids.",
    description: "Planned: generate cages, operators, and solver-friendly validation metadata.",
    category: "numbers",
    status: "planned",
    tags: ["numbers", "arithmetic", "cages"],
    defaultWidth: 6,
    defaultHeight: 6,
    minWidth: 4,
    maxWidth: 9,
    minHeight: 4,
    maxHeight: 9,
  },
  {
    id: "minesweeper",
    title: "Minesweeper",
    tagline: "Risky reveal logic and probability surfaces.",
    description: "Planned: generate minefields with first-click safety and solver annotations.",
    category: "grid",
    status: "planned",
    tags: ["grid", "probability", "classic"],
    defaultWidth: 10,
    defaultHeight: 10,
    minWidth: 8,
    maxWidth: 16,
    minHeight: 8,
    maxHeight: 16,
  },
  {
    id: "slitherlink",
    title: "Slitherlink",
    tagline: "Loop constraints around numbered cells.",
    description: "Planned: generate loop puzzles with uniqueness checks and path constraints.",
    category: "logic",
    status: "planned",
    tags: ["loop", "logic", "constraints"],
    defaultWidth: 7,
    defaultHeight: 7,
    minWidth: 5,
    maxWidth: 12,
    minHeight: 5,
    maxHeight: 12,
  },
];

export const getPuzzleDefinition = (id: PuzzleId) =>
  puzzleCatalog.find((puzzle) => puzzle.id === id) ?? puzzleCatalog[0];

export const isGeneratable = (puzzle: PuzzleDefinition) => puzzle.status !== "planned";
